dist: trusty
sudo: true
language: c++
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

install:
  - sudo apt-get install xorg-dev libglu1-mesa-dev

script:
  - CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0
  - cmake .
  - cmake --build . -- -j2